### ISSUE TITLE
docker-compose.yml

### ISSUE THREAD

**Issue by mircoh** [robbertkl/docker-roundcube#11]
Hi,

do you have such a file?

Thanks!

**Comment by robbertkl** [comment]
I suggest you read the Docker and/or Docker Compose documentation on how to add this to your `docker-compose.yml`. It's quite easy, just use the settings belonging to the arguments you use for your `docker run` command.

I cannot give you "such a file", as it depends on your setup: what compose file format version you're using, how you're dealing with persistent data (volumes), what environment variables you're using to configure roundcube, etc.

**Comment by mircoh** [comment]
Thanks for your answer, you are right.
I tried this one:

```yaml
roundcube:
    image: robbertkl/roundcube
    ports:
        - '88:80'
    container_name: roundcube
    volumes:
        - ./roundcube-data:/var/www/db
    environment:
        - ROUNDCUBE_DEFAULT_HOST=my-external-ip
        - ROUNDCUBE_SMTP_SERVER=my-external-ip
    restart: always
```

But it's not changing the IP address in the config.inc.php, and so can not access to my docker with dovecot.

Thanks for your help!
