### ISSUE TITLE
docker-compose.yml with ssl/tls

### ISSUE THREAD

**Issue by nalakawula** [robbertkl/docker-roundcube#13]
Hi robbert, you make great work. Thank you.
I created a docker-compose.yml if one day somebody need an example.
```yaml
roundcube:
    image: robbertkl/roundcube
    ports:
        - '80:80'
    container_name: roundcube
    volumes:
        - ./roundcube-data:/var/www/db
    environment:
        - ROUNDCUBE_DEFAULT_HOST=tls://mail.yourdomain.tld
        - ROUNDCUBE_SMTP_SERVER=tls://mail.yourdomain.tld
    restart: always
```

Thank you very much
